

CREATE TABLE IF NOT EXISTS users
(
 userID   int NOT NULL GENERATED BY DEFAULT AS IDENTITY (
 increment 2
 start 14532
 ),
 userName varchar(255) NOT NULL,
 password varchar(255) NOT NULL,
 name     varchar(255) NOT NULL,
 CONSTRAINT PK_5 PRIMARY KEY ( userID )
);


