

CREATE TABLE IF NOT EXISTS moods
(
 moodTitle varchar(50) NOT NULL,
 color     varchar(50) NOT NULL,
 moodID    int NOT NULL GENERATED BY DEFAULT AS IDENTITY (
 start 135
 ),
 CONSTRAINT PK_12 PRIMARY KEY ( moodID )
);

